### ISSUE TITLE
Create express server to cache financial information

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/insights#13]

**Comment by LoznianuAnamaria** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/insights/13?planning-poker) with Zenhub @mariacarmina @mihaisc

**Comment by mariacarmina** [comment]
@mihaisc can you share the API that you found?

**Comment by mariacarmina** [comment]
API: https://stock-api.oceanprotocol.com/stock/stock.json
GitHub repo: https://github.com/oceanprotocol/stock-api
The URL is validated and I could create the dataset based un the API URL https://market.oceanprotocol.com/asset/did:op:081f3577ed4a933b3764a02a9e5a15c67258afa4112abc0d158386455fe08345
