### ISSUE TITLE
Fix magic link issues

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/insights#23]
Currently, we've done a lot of things to integrate and make insights work with Magic Link but there are still some features & bugs we need to address. 
- [x] Metamask login is not working (See screenshot for error)
- [x] Currently some transactions are failing from time to time: make sure transactions are working
- [x] This is a weird issue 🤔 Magic transactions fail when a transaction is fired but the previous transaction popup is still displayed. If the popup is manually dismissed, the transactions go as expected but if the popup is not manually closed, the next transaction will fail (See attachments)
<img width="1507" alt="Screenshot 2023-10-31 at 14 57 37" src="https://github.com/oceanprotocol/insights/assets/84312885/df5774de-c2c9-42d8-bd33-af227e0aae00">

**Comment by LoznianuAnamaria** [comment]
@tom1145 update for the last issue with closing up the popup. I've talked with the Magic team and it seems it's a bug on their end. We are waiting for an update.

**Comment by tom1145** [comment]
> @tom1145 update for the last issue with closing up the popup. I've talked with the Magic team and it seems it's a bug on their end. We are waiting for an update.

Hello! I think it's from the wagmi + magic link integration, I also tried this [demo repo](https://github.com/magiclabs/wagmi-magic-connector#:~:text=https%3A//github.com/Royal%2Dlobster/vanilla%2Dmagic%2Dexample) recommended by magic labs and there it seems to be the same issue. Now I'm only using the Magic link without wagmi, and it works. Currently, I'm working on integrating the provider context that I made with the app. You can test [here](https://github.com/oceanprotocol/insights/pull/40) the progress so far. Thanks!
