### ISSUE TITLE
Creating an algorithm for generating PDFs

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/insights#8]
Very nice tech explanation [here](https://medium.com/@meet.paija/generating-pdf-report-in-nodejs-pdfkit-chartjs-handlebars-puppeteer-e64926fd380)

Demo response [here](https://gist.githubusercontent.com/mihaisc/b0b4c9405dd8fd2d6058c4a69441b877/raw/6868a4139b29e38f0eb8e93b209d2439ee08f464/stock.json) (this should be published as a compute asset until i publish the real one connected to the API) 

API documentation [here](https://polygon.io/docs/stocks/get_v2_aggs_grouped_locale_us_market_stocks__date)

To show in pdf: 
- top 10 by close price ( `c` in response) : bar chart with price
- top 10 by trading volume ( `v` in response) : table, show all data available
- top worst 10 by trading volume ( `v` in response): same

**Comment by mihaisc** [comment]
@mihaisc define data/api and the structure of the document

**Comment by mihaisc** [comment]
description updated

**Comment by mariacarmina** [comment]
Created & pushed the algorithm here https://github.com/oceanprotocol/c2d-examples/blob/main/generating_pdf_report/generatePdfReport.js

PDF Final format:
[report.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUVuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4b923df6076f260eef02f7af204df3bcc20803b/report.pdf)

Needs testing on market side/ocean.js on remote network.

**Comment by mihaisc** [comment]
The pdf needs some work. i'll update with proper feedback

**Comment by mariacarmina** [comment]
Ok, I'll wait for the final feedback and I'll do the changes afterwards. Thank you.

UPDATE: pushed the docker image on our registry `oceanprotocol/algo_dockers:generating-pdf-report` on DockerHub

**Comment by mariacarmina** [comment]
Refactored PDF:

[report.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNQQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd35d8a2614a67cc76274227b2949fa7c2070e94/report.pdf)

Tested on market, it worked and all the ements are shown properly.
https://market.oceanprotocol.com/asset/did:op:0e5ff048ad4c4a24f8c40b6f5b84763a0edaf5887abc88d6f9018e4ca526814a
